### ISSUE TITLE
绿灯申请

### ISSUE THREAD

**Issue by beixiangzhixia** [Corn-Pig/Backrooms-Miraheze-CN#2]
#### 必选项
您需要勾选下列所有选项（在[ ]中填X）:

- [X] 我拥有写作这篇文章的能力。
- [X] 我已经构思好了文章。
- [X] 我保证遵守站规。
- [X] 我了解后室。

#### 非必选项
请如实勾选下列选项（在[ ]中填X）:

- [ ] 这篇文章从英文站翻译，并且征得原作者同意。
- [ ] 我未满12岁，但是具备写作能力。
- [ ] 这篇文章曾经被删除过，这是重写。
- [ ] 我已经被封禁，需要代发。

**文章基本信息:**

请填写以下所有选项

- 题目/暂定题目: Level 43.2
- 文章类型（如实体、物品……）: 无面人
- 简介:独立的特殊子层级

请如实填写下列选项（没有请画“/”）

- 合著人:/
- 曾用名:/
- 英站页面名称/链接:/

**个人信息**
- 用户名:beixiangzhixia
- 语言变体（我们会提供转换服务，请在[]内打X）:
- [X] 简体/zh-hans
- [ ] 繁體/zh-hant

**备注：**

**Comment by Corn-Pig** [comment]
不通过，文章类型是填写上“实体”或者“层级”这几个字

**Comment by Corn-Pig** [comment]
申请失败，简介过于简洁
